site_name: DCI 101 course website
base_url: https://mackenziekbrooks.github.io/dci101-f22

theme: 
  name: 
  custom_dir: mkdocs_gitbook/

features:
  - tabs
    #- instant

extra_css: 
  - styles/website.css


plugins:
  - search

markdown_extensions:
    - toc:
        permalink: "#"

nav:
  - Schedule: schedule.md
  - Assignments: assignments.md
  - Week 1: week1.md
