site_name: DCI 101 - Fall 2022
base_url: https://mackenziekbrooks.github.io/dci101-f22

theme: 
  name: material

  features:
      - navigation.tabs
      - navigation.sections

  palette: 
    primary: lime    


plugins:
  - search

markdown_extensions:
    - toc:
        permalink: "#"

nav:
  - Course Info: index.md
  - Schedule:
    - Week 1: schedule/week1.md
    - Week 1 w/ jury duty: schedule/week1-juryduty.md
    - Week 2: schedule/week2.md
  - Assignments: assignments.md
